#!/usr/bin/env python

import libdircmp
import argparse
import re
import time

def find( pattern, directory, index, commonRootLen, args ):
    color_green = '\033[92m'
    color_red   = '\033[91m'
    color_blue = '\033[94m'
    color_brown = '\033[0;33m'
    color_end   = '\033[0m'

    print( "searching %s..." % pattern )
    lastOutput = time.time()
    counter = 0
    regex = re.compile( pattern )
    findings = []
    for path in index:
        fileId = index[path]
        match = regex.search( fileId['path'] )
        if match:
            groups = []
            groupCount =  len( match.groups() )
            for i in range( 1, groupCount+1 ):
                if match.start(i) != -1:
                    groups.append( match.span(i) )
            if not groups:
                groups.append( match.span() )
            findings.append( (fileId, groups) )

        counter += 1
        if time.time() - lastOutput > 10:
            print( '%i/%i...' % (counter, len(index)) )
            lastOutput = time.time()
    findings = sorted( findings, key = lambda s: s[0]['path'].lower() )
    print( "results:" )
    directoriesFound = []
    for finding in findings:
        fileId = finding[0]
        groups = finding[1]
        path = fileId['path']

        if fileId['isDir']: directoriesFound.append( path + '/' )

        normalColor = color_brown if fileId['isDir'] else color_blue
        text = ''
        if groups[0][0] == 0 and groups[0][1] == len( path ): # match everything -> do not colorize
            index = commonRootLen
        else:
            firstGroupIndex = groups[0][0]
            index = 0 if firstGroupIndex < commonRootLen else commonRootLen
            for group in groups:
                if index < group[0]: text += normalColor + path[index:group[0]] + color_end
                text += color_green + path[group[0]:group[1]] + color_end
                index = group[1]
        text += normalColor
        if index < len(path): text += path[index:]
        if fileId['isDir']: text += '/'
        text += color_end
        print( '%s (%s)' % (text, libdircmp.formatMemory( fileId['size'] )) )
    print( "%s%i%s results found (%i files, %i directories)." % (color_red, len(findings), color_end, len(findings)-len(directoriesFound), len(directoriesFound)) )
    print( "calculating size..." )
    size_all = 0
    size_files = 0
    for finding in findings:
        fileId = finding[0]
        path = fileId['path']
        alreadyIncluded = False
        for d in directoriesFound:
            if path[:len(d)] == d:
                alreadyIncluded = True
                break
        if not fileId['isDir']:
            size_files += fileId['size']
        if not alreadyIncluded:
            size_all += fileId['size']
    print( "total size: %s%s%s" % (color_red, libdircmp.formatMemory( size_all ), color_end) )
    if size_all != size_files:
        print( "files only: %s%s%s" % (color_red, libdircmp.formatMemory( size_files ), color_end) )

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument( 'path', help = 'directory or json file' )
    parser.add_argument( '--find', help = 'find paths (regex match)' )
    parser.add_argument( '--only', action = 'append', help = 'include paths (exact match); only on directory scans' )
    parser.add_argument( '--skip', action = 'append', help = 'exclude paths (exact match); only on directory scans' )
    parser.add_argument( '--save', help = 'only on directory scans' )
    parser.add_argument( '--exclude', action = 'append', help = 'exclude paths (regex match)' )
    parser.add_argument( '--include', action = 'append', help = 'include paths only (regex match)' )
    args = parser.parse_args()

    (directory, index, commonRootLen) = libdircmp.scan(
        args.path, None, '', args.save, args
        )

    if args.find:
        find( args.find, directory, index, commonRootLen, args )

if __name__ == "__main__":
    main()